### ISSUE TITLE
Succession of this project to Thruster?

### ISSUE THREAD

**Issue by naturallymitchell** [tokio-rs/tokio-minihttp#33]
How well does [Thruster](https://github.com/trezm/Thruster) follow the goals of this project?

**Comment by carllerche** [comment]
I do not understand the question

**Comment by naturallymitchell** [comment]
As I understand it, Thruster is based on tokio-minihttp.  A friend told me, "Thrusted seems to be not only a framework but a utility to create a project structure with organization and files for connecting to a DB, the migration files and so on."  So, at first I was wondering if that project replaces this one, but now it seems more like a fork that goes in a different direction.

@carllerche , Perhaps I could just ask you what is the future of this project, and of any potential tokio-http server more than a mini one?

**Comment by trezm** [comment]
Just happened upon this issue -- maintainer of Thruster here! 

Thruster was largely based on this project to start and, has since, built up around it and changed a fair bit. That being said, I am also curious to hear about the future plans for this repository and whether it stands to be a simple example of a fast tokio http server or whether it will maintain updates as tokio versions increase.

Happy to help contribute if necessary! Perhaps if the plan is to continue updates, we can migrate Thruster back to using a pure tokio-minihttp core.

Anyhow, long winded way of saying, I am also curious about the future of this project!

**Comment by carllerche** [comment]
As per the readme:

> This library is a proof-of-concept implementation of a simple HTTP/1.1 server using Tokio.
>
> The goal of the library is to demo the simplicity of implementing a protocol with Tokio. This is part of an effort of experimenting with multiple IO strategies in Rust in order to try to figure out the best path forward.

This lib is only an example / proof of concept. It will not evolve into a full HTTP server impl. For that, there is hyper.
